In [1]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
df = pd.read_excel("NovaTech_Sales_Raw_Data.xlsx")

In [4]:
#Remove duplicates
df = df.drop_duplicates()

In [5]:
type(df)

pandas.DataFrame

In [6]:
df.columns = df.columns.str.strip()

for col in df.select_dtypes(include=['object', 'string']).columns:
    df[col] = df[col].str.strip()

In [7]:
df.head()

,Order ID,Order Date,Region,State,Customer Segment,Sales Channel,Salesperson,Category,Product,Quantity,Unit Price (INR),Discount (%),Gross Sales (INR),Discount Amount (INR),Net Sales (INR),Cost (INR),Profit (INR)
0,ORD-10002,2025-04-13,West,Goa,Small Business,Retail Store,Kiran,Accessories,Wireless Mouse,11,2500,10,27500,2750,24750,19990.84,4759.16
1,ORD-10003,2026-01-21,South,Telangana,Small Business,Retail Store,Aarav,Monitors,NovaView 27,10,27100,5,271000,13550,257450,210245.56,47204.44
2,ORD-10004,2026-05-20,North,Haryana,Consumer,Direct Sales,Priya,Monitors,NovaView 24,9,34100,2,306900,6138,300762,209995.67,90766.33
3,ORD-10005,2026-01-23,South,Karnataka,Consumer,Direct Sales,Priya,Laptops,NovaBook Air,10,71600,15,716000,107400,608600,480128.66,128471.34
4,ORD-10006,2025-12-04,East,Jharkhand,Consumer,Direct Sales,Aarav,Smartphones,Nova X1,7,66600,10,466200,46620,419580,321314.97,98265.03

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Order ID               600 non-null    str
 1   Order Date             600 non-null    datetime64[us]
 2   Region                 600 non-null    str
 3   State                  594 non-null    str
 4   Customer Segment       596 non-null    str
 5   Sales Channel          600 non-null    str
 6   Salesperson            600 non-null    str
 7   Category               600 non-null    str
 8   Product                600 non-null    str
 9   Quantity               600 non-null    int64
 10  Unit Price (INR)       600 non-null    int64
 11  Discount (%)           600 non-null    int64
 12  Gross Sales (INR)      600 non-null    int64
 13  Discount Amount (INR)  600 non-null    int64
 14  Net Sales (INR)        600 non-null    int64
 15  Cost (INR)             600 non-null    float64
 16  Profit (INR)           600 non-null    float64
dtypes: datetime64[us](1), float64(2), int64(6), str(8)
memory usage: 79.8 KB

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Order ID               600 non-null    str
 1   Order Date             600 non-null    datetime64[us]
 2   Region                 600 non-null    str
 3   State                  594 non-null    str
 4   Customer Segment       596 non-null    str
 5   Sales Channel          600 non-null    str
 6   Salesperson            600 non-null    str
 7   Category               600 non-null    str
 8   Product                600 non-null    str
 9   Quantity               600 non-null    int64
 10  Unit Price (INR)       600 non-null    int64
 11  Discount (%)           600 non-null    int64
 12  Gross Sales (INR)      600 non-null    int64
 13  Discount Amount (INR)  600 non-null    int64
 14  Net Sales (INR)        600 non-null    int64
 15  Cost (INR)             600 non-null    float64
 16  Profit (INR)           600 non-null    float64
dtypes: datetime64[us](1), float64(2), int64(6), str(8)
memory usage: 79.8 KB

In [10]:
df.isnull().sum()

Order ID                 0
Order Date               0
Region                   0
State                    6
Customer Segment         4
Sales Channel            0
Salesperson              0
Category                 0
Product                  0
Quantity                 0
Unit Price (INR)         0
Discount (%)             0
Gross Sales (INR)        0
Discount Amount (INR)    0
Net Sales (INR)          0
Cost (INR)               0
Profit (INR)             0
dtype: int64

In [11]:
df['State'] = df['State'].fillna('Unknown')
df['Customer Segment'] = df['Customer Segment'].fillna('Unknown')

In [12]:
df.isnull().sum()

Order ID                 0
Order Date               0
Region                   0
State                    0
Customer Segment         0
Sales Channel            0
Salesperson              0
Category                 0
Product                  0
Quantity                 0
Unit Price (INR)         0
Discount (%)             0
Gross Sales (INR)        0
Discount Amount (INR)    0
Net Sales (INR)          0
Cost (INR)               0
Profit (INR)             0
dtype: int64

In [13]:
# Time features

df['Year'] = df['Order Date'].dt.year
df['Quarter'] = 'Q' + df['Order Date'].dt.quarter.astype(str)
df['Month'] = df['Order Date'].dt.month_name()
df['Month Number'] = df['Order Date'].dt.month

In [14]:
df[['Order Date','Year','Quarter','Month','Month Number']].head()

  Order Date  Year Quarter     Month  Month Number
0 2025-04-13  2025      Q2     April             4
1 2026-01-21  2026      Q1   January             1
2 2026-05-20  2026      Q2       May             5
3 2026-01-23  2026      Q1   January             1
4 2025-12-04  2025      Q4  December            12

In [15]:
df['Profit Margin %'] = (
    df['Profit (INR)'] /
    df['Net Sales (INR)']
) * 100

In [16]:
df[['Net Sales (INR)','Profit (INR)','Profit Margin %']].head()

   Net Sales (INR)  Profit (INR)  Profit Margin %
0            24750       4759.16        19.228929
1           257450      47204.44        18.335382
2           300762      90766.33        30.178789
3           608600     128471.34        21.109323
4           419580      98265.03        23.419856

In [17]:
df['Profit Per Unit'] = (
    df['Profit (INR)'] /
    df['Quantity']
)

In [18]:
df[['Quantity','Profit (INR)','Profit Per Unit']].head()

   Quantity  Profit (INR)  Profit Per Unit
0        11       4759.16       432.650909
1        10      47204.44      4720.444000
2         9      90766.33     10085.147778
3        10     128471.34     12847.134000
4         7      98265.03     14037.861429

In [19]:
df['Discount Category'] = pd.cut(
    df['Discount (%)'],
    bins=[-1,0,5,10,20],
    labels=[
        'No Discount',
        'Low Discount',
        'Medium Discount',
        'High Discount'
    ]
)

In [20]:
df[['Discount (%)','Discount Category']].head(10)

   Discount (%) Discount Category
0            10   Medium Discount
1             5      Low Discount
2             2      Low Discount
3            15     High Discount
4            10   Medium Discount
5            12     High Discount
6             8   Medium Discount
7            12     High Discount
8             5      Low Discount
9             8   Medium Discount

In [21]:
df['High Value Order'] = df['Net Sales (INR)'].apply(
    lambda x: 'Yes' if x >= 500000 else 'No'
)

In [22]:
df[['Net Sales (INR)','High Value Order']].head(10)

   Net Sales (INR) High Value Order
0            24750               No
1           257450               No
2           300762               No
3           608600              Yes
4           419580               No
5            41536               No
6           344080               No
7           220176               No
8           445550               No
9            51704               No

In [23]:
df[['Year',
    'Quarter',
    'Month',
    'Month Number',
    'Profit Margin %',
    'Profit Per Unit',
    'Discount Category',
    'High Value Order']].head()

,Year,Quarter,Month,Month Number,Profit Margin %,Profit Per Unit,Discount Category,High Value Order
0,2025,Q2,April,4,19.228929,432.650909,Medium Discount,No
1,2026,Q1,January,1,18.335382,4720.444000,Low Discount,No
2,2026,Q2,May,5,30.178789,10085.147778,Low Discount,No
3,2026,Q1,January,1,21.109323,12847.134000,High Discount,Yes
4,2025,Q4,December,12,23.419856,14037.861429,Medium Discount,No

In [24]:
df.to_excel('NovaTech_Cleaned_Data.xlsx', index=False)

print("NovaTech_Cleaned_Data.xlsx saved successfully")

NovaTech_Cleaned_Data.xlsx saved successfully

In [25]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (2.1.1)
Requirement already satisfied: psycopg2-binary in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (2.9.13)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (4.16.0)

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [26]:
import sqlalchemy
import psycopg2

print("Libraries Installed Successfully")

Libraries Installed Successfully

In [1]:
import pandas as pd
from sqlalchemy import create_engine

# Step 1: Load your CSV dataset into a pandas DataFrame
file_path = r"C:\Users\ASUS\Downloads\NovaTech_Cleaned_Data.xlsx"
df = pd.read_excel(file_path)

# Step 2: Set up PostgreSQL connection details
username = "postgres"
password = "210750"
host = "localhost"
port = "5432"
database = "NovaTech_db"

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

# Step 3: Load DataFrame into PostgreSQL
table_name = "sale"
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(
    f"Data successfully loaded into table '{table_name}' in database"
    f" '{database}'."
)

Data successfully loaded into table 'sale' in database 'NovaTech_db'.